# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [2]:
# ejercicio 1
a = np.array([1, 2, 3, 4])
resultado = not (a == 0).any()
print(resultado)

True


In [3]:
# ejercicio 2
a = np.array([0, 0, 2, 0])
resultado = np.any(a != 0)
print(resultado)

True


In [9]:
# ejercicio 3
a = np.array([1, 2, np.nan, np.inf])
nan = np.isnan(a)
inf = np.isinf(a)
nan, inf



(array([False, False,  True, False]), array([False, False, False,  True]))

In [11]:
# ejercicio 4
a = np.array([1, 2, np.nan, np.inf])
resultado = np.any(np.isinf(a) | np.isnan(a))
print(resultado)

True


In [12]:
#ejercicio 5
a = np.array([1, np.nan, 3])
resultado = np.any(np.isnan(a))
print(resultado)

True


In [13]:
#ejercicio 6
import numpy as np

a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

# Mayor que
mayor = a > b
print("a > b:", mayor)  # [False False  True]

# Mayor o igual que
mayor_igual = a >= b
print("a >= b:", mayor_igual)  # [False  True  True]

# Menor que
menor = a < b
print("a < b:", menor)  # [ True False False]

# Menor o igual que
menor_igual = a <= b
print("a <= b:", menor_igual)  # [ True  True False]

# Igualdad
igual = a == b
print("a == b:", igual)  # [False  True False]

# Diferente de
diferente = a != b
print("a != b:", diferente)  # [ True False  True]


a > b: [False False  True]
a >= b: [False  True  True]
a < b: [ True False False]
a <= b: [ True  True False]
a == b: [False  True False]
a != b: [ True False  True]


In [14]:
# ejercicio 7
import numpy as np

# Crear el arreglo
a = np.array([1, 7, 13, 105])
print("Arreglo:", a)

# Cantidad de memoria que ocupa (en bytes)
memoria_bytes = a.nbytes
print(f"Memoria total: {memoria_bytes} bytes")

# Memoria por elemento
memoria_por_elemento = a.itemsize
print(f"Memoria por elemento: {memoria_por_elemento} bytes")

# También se puede obtener así:
print(f"Forma alternativa - memoria total: {a.size * a.itemsize} bytes")


Arreglo: [  1   7  13 105]
Memoria total: 32 bytes
Memoria por elemento: 8 bytes
Forma alternativa - memoria total: 32 bytes


In [15]:
# ejercicio 8
aceros = np.zeros(10)
aunos = np.ones(10)
acincos = np.full(10, 5)

aceros, aunos, acincos


(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [16]:
# ejercicio 9
arreglo1 = np.arange(30, 71)
print("Con arange:", arreglo1)

Con arange: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [17]:
# ejercicio 10
pares1 = np.arange(30, 71, 2)
print("Con arange paso 2:", pares1)

Con arange paso 2: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [18]:
# ejercicio 11
identidad2 = np.eye(3)
print("\nCon eye():")
print(identidad2)


Con eye():
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
# ejercicio 12
import numpy as np

a = np.random.rand()
print("Número aleatorio con rand():", a)


Número aleatorio con rand(): 0.1225269221857499


In [3]:
# ejercicio 13
import numpy as np


a = np.random.randn(15)
print("15 números de normal estándar (randn):")
print(a)

15 números de normal estándar (randn):
[ 0.10391741  0.87062487 -0.193765   -1.43731223  2.3950763   1.27154352
 -0.31909765  0.46537346 -0.39090002 -0.69684161 -1.90182029  0.00691482
  1.74078428  0.16696574 -0.39523253]


In [4]:
# ejercicio 14

import numpy as np

a = np.arange(15, 56)
a[1:-1]



array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [5]:
# ejercicio 15
import numpy as np
a = np.linspace(5, 50, 10)
a


array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [7]:
# ejercicio 16

import numpy as np


a = np.arange(21)
a[9:16] = -a[9:16]
a


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [8]:
# ejercicio 17
import numpy as np


a = np.array([1, 2, 3])
print("Arreglo NumPy:", a)
print("Tipo:", type(a))

lista_python = a.tolist()
print("\nLista Python:", lista_python)
print("Tipo:", type(lista_python))

Arreglo NumPy: [1 2 3]
Tipo: <class 'numpy.ndarray'>

Lista Python: [1, 2, 3]
Tipo: <class 'list'>


In [9]:
# ejercicio 18
import numpy as np


l = [1, 2, 3]
print("Lista Python:", l)
print("Tipo:", type(l))


arreglo_numpy = np.array(l)
print("\nArreglo NumPy:", arreglo_numpy)
print("Tipo:", type(arreglo_numpy))


Lista Python: [1, 2, 3]
Tipo: <class 'list'>

Arreglo NumPy: [1 2 3]
Tipo: <class 'numpy.ndarray'>


In [10]:
# ejercicio 19

import numpy as np


a = np.array([[1, 2], [3, 4]])
print("Matriz original:")
a

resultados = a % 2 == 0
print("\nMatriz de resultados (True = par, False = impar):")
print(resultados)

Matriz original:

Matriz de resultados (True = par, False = impar):
[[False  True]
 [False  True]]


In [11]:
# ejercicio 20
import numpy as np

m = np.array([[1, 2, 3], [4, 5, 6]])


filas, columnas = m.shape

print("Matriz:")
print(m)
print(f"\nNúmero de filas: {filas}")
print(f"Número de columnas: {columnas}")
print(f"Forma completa (shape): {m.shape}")


Matriz:
[[1 2 3]
 [4 5 6]]

Número de filas: 2
Número de columnas: 3
Forma completa (shape): (2, 3)
